name: docs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: podman info and prior to startin pod
      run: |
        podman version
        sudo sysctl -w net.ipv4.ip_unprivileged_port_start=80
        make hosts
    - name: xqerl up and flying
      run: make up
    - name: checks - ps, log, top
      run: |
        podman ps --pod --all
        printf %60s | tr ' ' '-' && echo
        podman logs xq | grep -oP "started_at: 'xqerl@127.0.0.1'"
        printf %60s | tr ' ' '-' && echo
        podman top xq
    - name: build site from sources
      run: make
    - name: build documentation
      run: |
        make docs
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        # git checkout gh-pages
        mkdir -p docs
        podman cp xq:/usr/local/xqerl/priv/static/assets/. ./docs
        # ls -lR docs
        git add docs/
        git status --porcelain
        git commit -am 'update docs'

