name: docs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: podman info and prior to startin pod
      run: |
        podman version
        sudo sysctl -w net.ipv4.ip_unprivileged_port_start=80
        make hosts
    - name: xqerl up and flying
      run: make up
    - name: build site from sources
      run: make
    - name: build documentation
      run: |
        make docs
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        podman cp xq:/usr/local/xqerl/priv/static/assets/. ./docs
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: docs # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
        #git clone git@github.com:grantmacken/glider.git _docs
        #cd _docs
        #git rm -rf *
        # podman cp xq:/usr/local/xqerl/priv/static/assets/. ./docs
        # git checkout docs
        # mkdir -p docs
        # touch .nojekyll
        # ls -lR docs
        # git add docs/
        # git status --porcelain
        # git commit -am 'update docs'
        # git push origin docs

